"""import runs and listing scope

Revision ID: 1aade07639f4
Revises: ae43c16243d4
Create Date: 2026-09-04 03:41:27.095968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aade07639f4'
down_revision: Union[str, Sequence[str], None] = 'ae43c16243d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=96), nullable=False),
    sa.Column('mode', sa.Enum('INCREMENTAL', 'FULL_SNAPSHOT', name='importmode', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'COMPLETED', 'FAILED', name='importrunstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('listings_seen', sa.Integer(), nullable=False),
    sa.Column('listings_created', sa.Integer(), nullable=False),
    sa.Column('listings_updated', sa.Integer(), nullable=False),
    sa.Column('listings_removed', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_runs_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_runs_scope'), ['scope'], unique=False)

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_scope', sa.String(length=96), nullable=True))
        batch_op.create_index(batch_op.f('ix_listings_source_scope'), ['source_scope'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_source_scope'))
        batch_op.drop_column('source_scope')

    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_runs_scope'))
        batch_op.drop_index(batch_op.f('ix_import_runs_data_source_id'))

    op.drop_table('import_runs')
    # ### end Alembic commands ###
