"""initial schema

Revision ID: 386f0ad1110e
Revises: 
Create Date: 2026-09-03 20:31:10.436402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386f0ad1110e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('source_type', sa.Enum('SYNTHETIC', 'CSV_IMPORT', 'RDW', 'MANUAL', name='datasourcetype', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_key'), ['key'], unique=True)

    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_type', sa.Enum('PRIVATE', 'DEALER', 'UNKNOWN', name='sellertype', native_enum=False, length=16), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_option_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label_nl', sa.String(length=96), nullable=False),
    sa.Column('category', sa.Enum('TRIM_PACKAGE', 'COMFORT', 'SAFETY', 'INFOTAINMENT', 'EXTERIOR', 'TOWING', 'OTHER', name='optioncategory', native_enum=False, length=16), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_option_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_option_definitions_key'), ['key'], unique=True)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=16), nullable=True),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.String(length=32), nullable=True),
    sa.Column('trim', sa.String(length=64), nullable=True),
    sa.Column('make_raw', sa.String(length=128), nullable=True),
    sa.Column('model_raw', sa.String(length=128), nullable=True),
    sa.Column('trim_raw', sa.String(length=128), nullable=True),
    sa.Column('body_type', sa.Enum('HATCHBACK', 'SEDAN', 'STATIONWAGON', 'SUV', 'COUPE', 'CABRIOLET', 'MPV', 'UNKNOWN', name='bodytype', native_enum=False, length=16), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL', 'DIESEL', 'HYBRID', 'PLUGIN_HYBRID', 'ELECTRIC', 'LPG', 'UNKNOWN', name='fueltype', native_enum=False, length=16), nullable=False),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATIC', 'UNKNOWN', name='transmission', native_enum=False, length=16), nullable=False),
    sa.Column('drivetrain', sa.Enum('FWD', 'RWD', 'AWD', 'UNKNOWN', name='drivetrain', native_enum=False, length=8), nullable=False),
    sa.Column('engine_description', sa.String(length=64), nullable=True),
    sa.Column('engine_displacement_cc', sa.Integer(), nullable=True),
    sa.Column('power_kw', sa.Integer(), nullable=True),
    sa.Column('power_hp', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('first_registration_date', sa.Date(), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('catalog_price_cents', sa.Integer(), nullable=True),
    sa.Column('source_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_generation'), ['generation'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_make'), ['make'], unique=False)
        batch_op.create_index('ix_vehicles_make_model_year', ['make', 'model', 'year'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_mileage_km'), ['mileage_km'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_trim'), ['trim'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_year'), ['year'], unique=False)

    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('external_reference', sa.String(length=96), nullable=False),
    sa.Column('asking_price_cents', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PRICE_REDUCED', 'REMOVED', 'LIKELY_SOLD', 'RELISTED', 'UNKNOWN', name='listingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_asking_price_cents'), ['asking_price_cents'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index('ix_listings_source_reference', ['data_source_id', 'external_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_listings_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_vehicle_id', sa.Integer(), nullable=False),
    sa.Column('asking_price_cents', sa.Integer(), nullable=True),
    sa.Column('estimated_market_value_cents', sa.Integer(), nullable=False),
    sa.Column('recommended_buy_price_low_cents', sa.Integer(), nullable=False),
    sa.Column('recommended_buy_price_high_cents', sa.Integer(), nullable=False),
    sa.Column('deal_classification', sa.Enum('EXCELLENT_DEAL', 'GOOD_DEAL', 'FAIR_PRICE', 'EXPENSIVE', 'VERY_EXPENSIVE', name='dealclassification', native_enum=False, length=24), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('comparable_count', sa.Integer(), nullable=False),
    sa.Column('widening_level', sa.Integer(), nullable=False),
    sa.Column('market_statistics', sa.JSON(), nullable=False),
    sa.Column('adjustments', sa.JSON(), nullable=False),
    sa.Column('confidence_factors', sa.JSON(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['target_vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuations_target_vehicle_id'), ['target_vehicle_id'], unique=False)

    op.create_table('vehicle_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['vehicle_option_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'definition_id', name='uq_vehicle_option')
    )
    with op.batch_alter_table('vehicle_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_options_definition_id'), ['definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_options_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('vehicle_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('mass_kg', sa.Integer(), nullable=True),
    sa.Column('towing_capacity_braked_kg', sa.Integer(), nullable=True),
    sa.Column('battery_capacity_kwh', sa.Integer(), nullable=True),
    sa.Column('electric_range_km', sa.Integer(), nullable=True),
    sa.Column('co2_emissions_gpkm', sa.Integer(), nullable=True),
    sa.Column('top_speed_kmh', sa.Integer(), nullable=True),
    sa.Column('apk_valid_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_specifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_specifications_vehicle_id'), ['vehicle_id'], unique=True)

    op.create_table('listing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asking_price_cents', sa.Integer(), nullable=False),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PRICE_REDUCED', 'REMOVED', 'LIKELY_SOLD', 'RELISTED', 'UNKNOWN', name='listingstatus', native_enum=False, length=16), nullable=False),
    sa.Column('raw_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_snapshots_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_snapshots_observed_at'), ['observed_at'], unique=False)

    op.create_table('valuation_comparables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valuation_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('adjusted_price_cents', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('differences', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['valuation_id'], ['valuations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuation_comparables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_comparables_valuation_id'), ['valuation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valuation_comparables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_comparables_valuation_id'))

    op.drop_table('valuation_comparables')
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_snapshots_observed_at'))
        batch_op.drop_index(batch_op.f('ix_listing_snapshots_listing_id'))

    op.drop_table('listing_snapshots')
    with op.batch_alter_table('vehicle_specifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_specifications_vehicle_id'))

    op.drop_table('vehicle_specifications')
    with op.batch_alter_table('vehicle_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_options_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_options_definition_id'))

    op.drop_table('vehicle_options')
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuations_target_vehicle_id'))

    op.drop_table('valuations')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_vehicle_id'))
        batch_op.drop_index('ix_listings_source_reference')
        batch_op.drop_index(batch_op.f('ix_listings_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_listings_external_reference'))
        batch_op.drop_index(batch_op.f('ix_listings_data_source_id'))
        batch_op.drop_index(batch_op.f('ix_listings_asking_price_cents'))

    op.drop_table('listings')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_year'))
        batch_op.drop_index(batch_op.f('ix_vehicles_trim'))
        batch_op.drop_index(batch_op.f('ix_vehicles_model'))
        batch_op.drop_index(batch_op.f('ix_vehicles_mileage_km'))
        batch_op.drop_index('ix_vehicles_make_model_year')
        batch_op.drop_index(batch_op.f('ix_vehicles_make'))
        batch_op.drop_index(batch_op.f('ix_vehicles_license_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicles_generation'))

    op.drop_table('vehicles')
    with op.batch_alter_table('vehicle_option_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_option_definitions_key'))

    op.drop_table('vehicle_option_definitions')
    op.drop_table('sellers')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_key'))

    op.drop_table('data_sources')
    # ### end Alembic commands ###
