"""store market basis on valuations

Revision ID: ae43c16243d4
Revises: 386f0ad1110e
Create Date: 2026-09-03 22:11:51.586217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae43c16243d4'
down_revision: Union[str, Sequence[str], None] = '386f0ad1110e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_basis_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.drop_column('market_basis_cents')

    # ### end Alembic commands ###
